from src.ciphers.rc import RC4
from collections import namedtuple
import pytest

RC4example = namedtuple('RC4example',
                        ['key', 'keystream', 'input', 'ciphertext'])


class TestAgainstExamples():
    examples = (RC4example('Key', 'eb9f7781b734ca72a719', 'Plaintext',
                           'bbf316e8d940af0ad3'),
                RC4example('Wiki', '6044db6d41b7', 'pedia', '1021bf0420'),
                RC4example('Secret', '04d46b053ca87b59', 'Attack at dawn',
                           '45a01f645fc35b383552544b9bf5'))

    @staticmethod
    def hexify(i: int) -> str:
        return hex(i).lstrip('0x').zfill(2)

    def get_keystream(self, key, length) -> str:
        """gets the keystream generated by RC4 pseudo-random algorithm"""
        return "".join(self.hexify(i) for i in RC4(key).prgen(length))

    def test_against_examples(self):
        for key, keystream, inp, cipher in self.examples:
            encoded = RC4(key).encode(inp)
            assert keystream == self.get_keystream(key, len(keystream) // 2)
            assert cipher == "".join(self.hexify(i) for i in encoded)
            assert inp == RC4(key).decode(encoded)


# --- test encode decode ---

# whitespace, weird, simple and 256 bytes
KEYS = ("\t\n \t\n"
        "some\tthing\n eles Qqę2πśð„’ę©something", "simple key",
        "".join(chr(i) for i in range(200, 456)))


def ed_helper(original):  # ed feels unfortunate because of certain dysfunction
    for key in KEYS:
        encoded = RC4(key).encode(original)
        assert original == RC4(key).decode(encoded)


def test_ed_weird():
    original = 'tes#^TEŋ ęß©t\n\tπś535ææœ ’æŋ’ðð’©ęþ'
    ed_helper(original)


def test_ed_simple():
    ed_helper("simple secret message")


@pytest.mark.slow
def test_ed_highunicode():
    """unicode characters except control/ASCII/Latin up to
    high surrogate weirdness"""
    ed_helper("".join(chr(i) for i in range(161, 55290)))

